Add a new category under the Azure Spring CLoud's Diagnose and solve …
Azure/Azure-AppServices-Diagnostics-Portal pull request #1004
Opened 2021-01-18 06:47 UTC by CaihuaRui

…prolems blade named Networking.

2021-01-19 13:33 UTC, bowen5 requested changes

2021-01-19 13:33 UTC, bowen5 commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.appplatform/spring/config.json
> +			"description": "Are you having issues when Azure Spring Cloud is placed in VNET? Are you blocking the outbound traffic to Azure Spring Cloud components for operating, maintaining and supporting th
Consider "Are you having network connectivity issues when Azure Spring Cloud is deployed in your own virtual network? Find out if you misconfigured the Private DNS Zone, Custom DNS Server or blocked required outbound traffics in your VNet injected service instance."

2021-01-19 13:33 UTC, bowen5 commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.appplatform/spring/config.json
> +			"keywords": ["VNET", "Private DNS Zone", "Firewall", "Subnet"],
["Virtual Network", "Custom DNS Server", "Private DNS Zone", "Firewall"]

2021-01-20 02:39 UTC, bowen5 approved these changes

2021-01-20 11:15 UTC, Sneezry approved these changes

2021-01-20 11:19 UTC, Sneezry commented
Invoke @nmallick1 to review this PR.

2021-01-20 17:29 UTC, nmallick1 requested changes

2021-01-20 17:29 UTC, nmallick1 commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.appplatform/spring/config.json
> +            "description": "Are you having network connectivity issues when Azure Spring Cloud is deployed in your own virtual network? Find out if you misconfigured the Private DNS Zone, Custom DNS
I think there is a typo here. I believe it should read traffic instead of traffics.

2021-01-21 16:25 UTC, nmallick1 approved these changes

2021-01-21 16:25 UTC, merged