APIM - Diagnose & Solve Blade
Azure/Azure-AppServices-Diagnostics-Portal pull request #1018
Opened 2021-01-26 23:16 UTC by rzhang628

2021-01-26 23:33 UTC, nmallick1 approved these changes
nitpick: JSON formatting/indentation seems off. Would it be possible to fix the indentation before merge?

2021-01-26 23:51 UTC, cindylovescoding commented
Hey @rzhang628  Could you share a screenshot for the new UI with this change?

2021-01-27 17:41 UTC, cindylovescoding approved these changes

2021-01-27 19:16 UTC, yunjchoi requested changes

2021-01-27 19:16 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/config.json
> +    "searchBarPlaceHolder": "Search Azure API Management Services"
Can you update the searchBarPlaceHolder text to: "Search for common problems or tools"

2021-01-27 19:16 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/config.json
> +        "Service down",
Title case missing

2021-01-27 19:16 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/config.json
> +      "description": "Found out if your API proxy and policy are misconfigured",
Found -> Find

2021-01-27 19:16 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/config.json
> +        "Service SKU",
Please take out "Service" in your keywords to avoid redundancy

2021-01-27 20:51 UTC, yunjchoi requested changes

2021-01-27 20:51 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/config.json
> +    "description": "Investigate how your API is performing, diagnose issues, and discover how to improve its reliability. Select the problem category that best matches the information or tool that yo
"description": "Investigate how your API is performing, diagnose issues, and discover how to improve its reliability.",
 
 Can we take out the second sentence? We've gotten feedback from the designer that this sentence doesn't add much value because the UI is self-explanatory.

2021-01-27 20:51 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/config.json
> +  "azureServiceName": "Azure API Management Service",
"azureServiceName": "API Management",

2021-01-27 20:51 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/config.json
> +        "Gateway Request"
"Gateway Requests"
Just a nitpick, but can we make the keyword plural to keep it consistent with "Gateway responses?"

2021-01-27 23:10 UTC, yunjchoi approved these changes

2021-01-29 23:52 UTC, merged