change config file and add category icon for Azure SignalR new genie experience
Azure/Azure-AppServices-Diagnostics-Portal pull request #1046
Opened 2021-02-26 02:40 UTC by ruimhu

-removed overall category 
-added quicklinks
-added overviewDetectorId for each existing category
-add a new icon

2021-02-26 18:06 UTC, XiaoxuHU commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/config.json
> +            "id": "availabilityandperformance",
How about changing category Id to "AvailabilityAndPerformanceSignalr" to be more clear ?

2021-02-26 18:06 UTC, XiaoxuHU commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/config.json
> +            "id": "resourcesusage",
Same here, add "Signalr" as suffix for category id

2021-03-01 03:23 UTC, XiaoxuHU approved these changes

2021-03-01 21:47 UTC, yunjchoi requested changes
I left some comments and suggestions on the PR mainly around the customer-facing category description and keywords. I tried to reduce the word count so it would render nicely with the new UI.

2021-03-01 21:47 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/config.json
> +            "keywords": [ "Resources", "connection count", "message count" ],
```suggestion
            "keywords": [ "SKU Plan", "Connection Count", "Message Count" ],

```

2021-03-01 21:47 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/config.json
> +            "description": "Are you trying to figure out your resource usage? You can see your resource usage here. ",
Can we reduce the word counts on the description?
```suggestion
            "description": "Find out the resource usage on your SignalR Service.",

```

2021-03-01 21:47 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/config.json
> +            "keywords": [ "Config Sever", "App Health", "Availability", "sdk" ],
Since availability is the title of the category, can we remove it to reduce redundancy and replace it with "Error Rate"? Also, I changed the last keyword to be in all caps.
```suggestion
            "keywords": [ "Config Sever", "App Health", "Error Rate", "SDK" ],

```

2021-03-01 21:47 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/config.json
>              "description": "Investigate issues with your azure signalr service. Find out the common causes and investigate in detail. ",
Can we reduce the word count for the description? 
```suggestion
            "description": "Investigate common issues impacting the health of your SignalR Service.",

```

2021-03-02 03:23 UTC, cindylovescoding approved these changes

2021-03-03 01:42 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/config.json
> +            "description": "Are you trying to figure out your resource usage? You can see your resource usage here. ",
Hi @ruimhu, is it possible to use the description I suggested? I tested the new descriptions you've added, but they don't take up the same number of lines, so the cards don't render as nicely.

2021-03-03 01:42 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/config.json
>              "description": "Investigate issues with your azure signalr service. Find out the common causes and investigate in detail. ",
Hi @ruimhu, is it possible to use the description I suggested? I tested the new descriptions you've added, but they don't take up the same number of lines, so the cards don't render as nicely.

2021-03-10 01:29 UTC, yunjchoi approved these changes

2021-03-15 22:10 UTC, merged