Logic apps genie v3
Azure/Azure-AppServices-Diagnostics-Portal pull request #1096
Opened 2021-03-30 21:48 UTC by yunjchoi

2021-03-30 23:56 UTC, khaled-zayed requested changes

2021-03-30 23:56 UTC, khaled-zayed commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.logic/workflows/config.json
> +			"description": "Get an overview about the most recent runs and their steps, troubleshoot, and identify possible improvements.",
How about 'Troubleshoot your most recent runs.'

2021-03-30 23:56 UTC, khaled-zayed commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.logic/workflows/config.json
> +			"description": "Review connector actions health to get the details on connector errors, timeouts, or any other unexpected behavior.",
'Investigate the health of your connectors.'

2021-03-31 20:02 UTC, yunjchoi commented
@khaled-zayed I added some extra words so that the content renders consistently in both tiles. 

![image](https://user-images.githubusercontent.com/49920477/113203742-4094c600-9221-11eb-998e-f2777f930477.png)

2021-04-02 17:33 UTC, khaled-zayed approved these changes

2021-04-02 21:52 UTC, XiaoxuHU approved these changes

2021-04-05 19:05 UTC, merged