Migrating ise to genie v3
Azure/Azure-AppServices-Diagnostics-Portal pull request #1140
Opened 2021-05-04 19:01 UTC by yunjchoi

2021-05-04 19:16 UTC, khaled-zayed requested changes

2021-05-04 19:16 UTC, khaled-zayed commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.logic/integrationServiceEnvironments/config.json
> +			"id": "provisioningdiagnosticsapim",
why apim?

2021-05-05 00:56 UTC, yunjchoi commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.logic/integrationServiceEnvironments/config.json
> +			"id": "provisioningdiagnosticsapim",
I was looking at the apim example and put apim by mistake :D

2021-05-05 15:56 UTC, XiaoxuHU approved these changes

2021-05-05 21:27 UTC, khaled-zayed approved these changes

2021-05-05 21:32 UTC, merged