hide gist version selector for graduation
Azure/Azure-AppServices-Diagnostics-Portal pull request #1409
Opened 2022-01-25 22:30 UTC by DarrelDonald

2022-01-25 22:32 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
> +      <fab-command-bar-item [style]="gistVersionVisibilityStyle" key="gistVersion" text="Gist version" [iconProps]="{ iconName: 'BackToWindow' }"
I don't think we meant to hide the button completely. This will confuse authors from the current experience. We should show the latest version of the gist.

2022-01-25 22:34 UTC, DarrelDonald commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
> +      <fab-command-bar-item [style]="gistVersionVisibilityStyle" key="gistVersion" text="Gist version" [iconProps]="{ iconName: 'BackToWindow' }"
i see. ill update this

2022-01-26 16:29 UTC, rekhaswaminathan requested changes

2022-01-26 16:29 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
> +        this.latestGistVersion = this.gistVersionOptions[0]["text"];
This is pulling from Github, isn't it? The latest version should come from devops for resources that have Graduation enabled.

2022-01-27 16:40 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
> +      <!-- <fab-dropdown [disabled]="!gistName" label="Gist version" (onChange)="gistVersionOnChange($event)"
do we need this commented code?

2022-01-27 16:40 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
> +    return this.invoke(path, HttpMethod.POST, body, false);
May be make this change for other APIs as well? (Get branches, Get resource config, etc) 
Ignore this comment if they already have `false` for cache

2022-01-27 16:40 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
> +        this.diagnosticApiService.getDetectorCode(`${this.gistVersionOptions[0]["title"]}/${this.gistVersionOptions[0]["title"]}.csx`, this.defaultBranch, this.resourceId).subscribe(gistCode => {
Why does this API needs to be called inside `githubService.getChangelist` ?

2022-01-27 16:42 UTC, rekhaswaminathan commented
@DarrelDonald Can you add a screenshot of how this will work for Graduation-Enabled scenarios vs  Non-Graduation Enabled scenarios?

2022-01-27 18:47 UTC, DarrelDonald commented
> @DarrelDonald Can you add a screenshot of how this will look for Graduation-Enabled scenarios vs Non-Graduation Enabled scenarios?

@rekhaswaminathan 
when there are no gists, this is shared for both scenarios
![image](https://user-images.githubusercontent.com/25857421/151422589-a8d63e78-7292-404d-8fdf-7657b10cfd4c.png)

no gist selected graduation enabled
![image](https://user-images.githubusercontent.com/25857421/151422846-7074a759-14cf-4c14-9e0e-9a282277c09a.png)

gist selected graduation enabled
![image](https://user-images.githubusercontent.com/25857421/151422924-d697efc6-fde7-45ea-8cc6-d1573249de31.png)

no gist selected non graduation enabled
![image](https://user-images.githubusercontent.com/25857421/151423644-d5aa4f49-45f3-437b-be03-2f34f70fd795.png)

gist selected non graduation enabled
![image](https://user-images.githubusercontent.com/25857421/151423808-22b2918d-9d59-4590-a509-21cac2a2feb1.png)

2022-01-27 18:48 UTC, rekhaswaminathan approved these changes

2022-01-27 18:48 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
> +  <fab-dialog *ngIf="!detectorGraduation || gists.length == 0" [hidden]="gistDialogHidden" (onDismiss)="dismissGistDialog()">
Does this mean for non-graduation scenarios, if a detector has no gists, we are hiding the gist diag?

2022-01-27 18:48 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
> +      <div class="mt-5">
nit: not sure if empty `<div class="mt-5">` is needed if it doesn't have any children inside

2022-01-27 18:52 UTC, rekhaswaminathan commented
Approved the PR with minor comments. Thanks Darrel! 👍

2022-01-27 18:59 UTC, DarrelDonald commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
> +  <fab-dialog *ngIf="!detectorGraduation || gists.length == 0" [hidden]="gistDialogHidden" (onDismiss)="dismissGistDialog()">
No, when there are no gists I'm using the same version of the gist dialog for both scenarios. There's another dialog for when graduation is enabled and there are gists available that will be shown instead of this one

2022-01-27 19:01 UTC, DarrelDonald commented on AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
> +    return this.invoke(path, HttpMethod.POST, body, false);
I was going to add it on the others after verifying if this actually fixes the issue. I can't reproduce the issue on my local so I need to test it in staging

2022-01-27 19:02 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
> +  <fab-dialog *ngIf="!detectorGraduation || gists.length == 0" [hidden]="gistDialogHidden" (onDismiss)="dismissGistDialog()">
Sounds good.

2022-01-27 19:02 UTC, merged