Apim/network status flow
Azure/Azure-AppServices-Diagnostics-Portal pull request #1631
Opened 2022-06-27 17:33 UTC by t-prayudu

Feature for backlog item [Connectivity Check tools](https://dev.azure.com/msazure/One/_workitems/edit/10570965). 
Satisfies work items
* Network connectivity check
* [VNet Check](https://dev.azure.com/msazure/One/_workitems/edit/14677327)
* [DNS Check](https://dev.azure.com/msazure/One/_workitems/edit/14661818)

2022-06-27 18:28 UTC, atuannguyen1101 requested changes

2022-06-27 18:28 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/Contract/APIMService.ts
> +export interface ApiManagementServiceResource {
In Azure, for contracts like this, properties is the only field that differentiate one from another, it make sense to create another Generic contract `export interface ArmContract<T>` . In this case, I saw that AppService already have this contract `ArmObj` in `armObj.ts`. We can utilize that

2022-06-27 18:28 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/Contract/NetworkSecurity.ts
> +export interface NetworkSecurityGroup {
Use `armOjb.ts`

2022-06-27 18:28 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/Contract/NetworkStatus.ts
> +export interface NetworkStatusContractByLocation {
Let's try to keep the contract naming in sync, `NetworkStatusByLocationContract`

2022-06-27 18:28 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/data/portRequirements.ts
> +    num: number | number[];
I would suggest just using `number[]`. Since in our use case, number is just number[] with one item and this implementation will only cause confusion in maintaining code. Same applies for below

2022-06-27 18:36 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/DnsFlow.ts
> +function getVnetResourceId(subnetResourceId: string): string {
Utilize descriptor parsing 
![image](https://user-images.githubusercontent.com/32973156/176011834-15a07dd8-0f4c-43af-8ca1-fd5162608ca3.png)

2022-06-27 19:01 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/dnsMismatchCheck.ts
> +        let invalidStatuses = networkStatuses.filter(status => status.networkStatus.dnsServers.some(dns => validDNSs.includes(dns)));
This only perform on the main locations, not all the locations. As we discussed earlier, to perform DNS check for subLocations, we need to retrieve information for the VNETs

2022-06-27 19:01 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/dnsMismatchCheck.ts
> +        let validDNSs = vnet.properties.dhcpOptions.dnsServers;
For the time being, if the list is empty, that mean custom DNS did not get set up, we can skip the check in that case

2022-06-28 16:46 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/Contract/APIMService.ts
> +export interface ApiManagementServiceResource {
resolved in commit cf13ce34073cce6bb33a8742c0e90519b1c2fa34

2022-06-28 16:47 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/Contract/NetworkSecurity.ts
> +export interface NetworkSecurityGroup {
resolved in commit cf13ce34073cce6bb33a8742c0e90519b1c2fa34

2022-06-28 16:47 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/Contract/NetworkStatus.ts
> +export interface NetworkStatusContractByLocation {
resolved in commit 79ae5c49e9870f2e6b2eee30d3fd4c02a75e9632

2022-06-28 19:43 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/DnsFlow.ts
> +export const NETWORK_API_VERSION = "2021-08-01";
Do we need these imports?

2022-06-28 19:43 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/DnsFlow.ts
> +export let statusMarkdown = {
Let's rename it as something clearer to its purpose, statusIconMarkdown or statusImageMarkdown

2022-06-28 19:43 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +    port2: number | null;
Don't need to define | null, number could be null as well

2022-06-28 19:57 UTC, atuannguyen1101 requested changes

2022-06-28 19:57 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +        (ip1 == "Internet" && ip2 != "VirtualNetwork") || (ip1 != "VirtualNetwork" && ip2 == "Internet");
Let's verify this with Samir, I think previously the talk was "most of the tags will be under Virtual Network, Internet is not under VNET"

2022-06-28 22:35 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/data/portRequirements.ts
> +    num: number | number[];
Fixed in commit 20e5644a60cf92028b09a81f72a1c3c23dd0d568

2022-06-28 22:36 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/DnsFlow.ts
> +function getVnetResourceId(subnetResourceId: string): string {
Fixed in commit 20e5644a60cf92028b09a81f72a1c3c23dd0d568

2022-06-28 22:37 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/dnsMismatchCheck.ts
> +        let validDNSs = vnet.properties.dhcpOptions.dnsServers;
fixed in commit 852c5e93a9581af8b74317aa758d0d7c8df20611

2022-06-28 22:39 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +    securityRules.sort((a, b) => a.properties.priority - b.properties.priority);
fixed in commit 2c9a7e3da13a4e8294678539dc070ac7d9d8a832

2022-06-28 22:39 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +    port2: number | null;
Fixed in commit 2c9a7e3da13a4e8294678539dc070ac7d9d8a832

2022-06-28 22:39 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +        if (ports == "*") {
fixed in commit 2c9a7e3da13a4e8294678539dc070ac7d9d8a832

2022-06-28 23:43 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +    port2: number | null;
Replaced `port1: number | null` type with `portLowerBound: number` and added a `ports: number[]` field to handle commas case. `portLowerBound` and `portUpperBound` will be `-1` when `ports` contains list of allowed ports since -1 does not qualify with any port.

2022-06-28 23:44 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/DnsFlow.ts
> +export let statusMarkdown = {
resolved in 2c9a7e3da13a4e8294678539dc070ac7d9d8a832

2022-06-29 19:18 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +        if (this.port2) {
fixed in 2c9a7e3da13a4e8294678539dc070ac7d9d8a832

2022-06-29 22:33 UTC, atuannguyen1101 commented
We will need Elizabeth and Chip to help us with wording and rephrasing sentences. Please also loop Vitalii into that meeting as he will help us providing context.

2022-06-29 22:39 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/DnsFlow.ts
> +export const NETWORK_API_VERSION = "2021-08-01";
We can create a file to hold Constants and mutual imported files. There are circular reference here (DnsFlow <-> dnsMismatchCheck.ts)

2022-06-29 22:41 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/DnsFlow.ts
> +        nsgRuleCheck(networkType, flowMgr, diagProvider, serviceResource);
Let's separate the Flow according to the plan here https://microsoft.sharepoint.com/teams/apimanagement/_layouts/OneNote.aspx?id=%2Fteams%2Fapimanagement%2FSiteAssets%2Fapimanagement%20Notebook&wd=target%28APIM%2BApiHub%20%28ColdFusion%5C%29.one%7C2C76D14A-2694-4704-9220-BD921C665CB0%2FPlan%5C%2Fgoal%7C7C32870F-1F6C-4DF8-988A-C6729C5D62ED%2F%29
onenote:https://microsoft.sharepoint.com/teams/apimanagement/SiteAssets/apimanagement%20Notebook/APIM+ApiHub%20(ColdFusion).one#[Plan/goal](onenote:https://microsoft.sharepoint.com/teams/apimanagement/SiteAssets/apimanagement%20Notebook/APIM+ApiHub%20(ColdFusion).one#Plan/goal&section-id={2C76D14A-2694-4704-9220-BD921C665CB0}&page-id={7C32870F-1F6C-4DF8-988A-C6729C5D62ED}&end)&section-id={2C76D14A-2694-4704-9220-BD921C665CB0}&page-id={7C32870F-1F6C-4DF8-988A-C6729C5D62ED}&end

2022-06-29 22:45 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/dnsMismatchCheck.ts
> +        let invalidStatuses;
Can we specify the location where the invalid status came from?

2022-06-29 22:54 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +    if (rule.properties.provisioningState != ProvisioningState.SUCCEEDED)
What is provisioningState here? Where do we have this condition from?

2022-06-29 23:03 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +    if (samePorts([-1], rule.properties.sourcePortRange || rule.properties.sourcePortRanges))
Interesting observation here :)

2022-06-29 23:13 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +    let fullRange = ports.includes(-1) && (portRange == "*" || portRange == "0-65536");
`portRange.includes` in case customers do some funny set up here :)

2022-06-29 23:14 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +        if (Array.isArray(ports)) {
Have we accounted for scenario `80, 8080-8081`?

2022-06-29 23:16 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/contracts/APIMService.ts
> +    properties: {
It's good that you pull in all the information here, but for reference in the future, we can just create the contract with fields we need then extend it later

2022-06-29 23:25 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/data/portRequirements.ts
> +export const stv1portRequirements: PortRequirements[] = [
Lots of overlaps here and I think they are the base requirements regardless of svt version, I'd recommend structure it like this for maintainability:
`const baseRequirements = [{}, {}]
const stv1portRequirements = [...baseRequirements , (extra requirement here)]
const stv1portRequirements = [...baseRequirements , (extra requirement here)]
`
For reference: https://budiirawan.com/typescript-destructuring-array/

2022-06-30 20:23 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +    if (rule.properties.provisioningState != ProvisioningState.SUCCEEDED)
The [provisioning state](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/network-security-groups/get#provisioningstate) can be in `deleting`, `failed`, or `updating` state as well in which case we do not want customers to keep seeing the rule as an issue (in case they went in and deleted the rule, etc.)

2022-07-05 21:09 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +    if (rule.properties.provisioningState != ProvisioningState.SUCCEEDED)
`ProvisioningState` can be `Deleting`, `Failed`, `Succeeded`, or `Updating`. Since NSG rules in transitioning states or failed states are not / will not be enforced, it makes sense to ignore them

2022-07-05 21:12 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/DnsFlow.ts
> +export const NETWORK_API_VERSION = "2021-08-01";
fixed in ce8f704a5595fdc384fc5b5201b8b4f06f09a54b

2022-07-05 21:14 UTC, t-prayudu commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +        if (Array.isArray(ports)) {
fixed in 82efe759f67fc59d8669dc761ba48fdf95cc7da8

2022-07-06 18:21 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/dnsMismatchCheck.ts
> +    console.log("status", invalidStatuses);
Remove this before merging

2022-07-06 18:23 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/dnsMismatchCheck.ts
> +        // should move await calls into Promise.all for good parallelism
what we want to do here is to perform batch call. We can verify with AppService team if they support it in this project. For now what we have is pretty good

2022-07-06 21:55 UTC, atuannguyen1101 approved these changes

2022-07-11 23:44 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/dnsMismatchCheck.ts
>      return uriDescriptor.resource;
Two return statement?

2022-07-12 00:17 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/routeTableCheck.ts
> +    let hasOmniQualifier = hasRouteTable && table.properties.routes.some(route => route.properties.addressPrefix.includes("/0")); // match 0 bits
We need to check for the specific route "0.0.0.0/0", not every prefix with "/0"

2022-07-12 18:43 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/dnsMismatchCheck.ts
> +        invalidStatusByLocation[serviceResource.location] = await getInvalidDnsByVNet(serviceResource.properties.virtualNetworkConfiguration, diagProvider, networkStatuses);
Why do we perform DNS check for all the network statuses using the same main location? Why did we decide to delete the usage of additional location? Also, we only perform one networkstatus compare for each location, so `networkStatuses` should be singular here.

2022-07-13 22:30 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/routeTableCheck.ts
> +        level: hasOmniQualifier ? checkResultLevel.warning : checkResultLevel.warning,
Hmm both warning?

2022-07-13 22:39 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +async function getVnetInfoView(
Let's also perform check for additionalLocations here, since we already got the format should not be very complex implementation

2022-07-18 18:49 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +    return fullRange || !ports.some((n) => pRange.has(n));
Well the question is what is the logic here? If there is some common elements between the requirement and rule, we return False?

2022-07-18 18:51 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/nsgCheck.ts
> +function sameIP(ip1: string, ip2: string) {
nit: It's a good practice to aways have a return-type declared (optional)

2022-07-19 23:25 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/dnsMismatchCheck.ts
> +            hidden: isTransitioning
Wait does that mean the button will not show at all if the current state is transitioning? Shouldn't it be "Disabled"?

2022-07-19 23:25 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/dnsMismatchCheck.ts
> +        let buttonText = isTransitioning ? "Configuration is updating" : "Apply Network Configuration";
Configuration is updating -> Service is updating

2022-07-19 23:27 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/networkStatusCheck.ts
> +                case 0: return statusIcon(StatusStyles.WarningIcon, "Stale");
Let's use the exact enum instead of the number here for readability. For example, case StatusStyles.{}

2022-07-19 23:34 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/apim-flows/checks/routeTableCheck.ts
> +    let hasRouteTable = !!(table && table.properties); // convert fals`y value to boolean
Interesting comment :)

2022-07-19 23:37 UTC, atuannguyen1101 commented on AngularApp/projects/diagnostic-data/src/lib/components/step-views/check-step-view/check.component.html
> +        [disabled]="check.action.hidden"
Oh so this is where the "hidden" come from, let's change it to "disable to reduce confusion"

2022-07-19 23:41 UTC, t-prayudu commented on AngularApp/projects/diagnostic-data/src/lib/components/step-views/check-step-view/check.component.html
> +        [disabled]="check.action.hidden"
`hidden` is a property of `StepView` that `ButtonStepView` inherits. I can add a `disabled` property but originally `ButtonStepView` used `hidden` as its `disabled` flag.

2022-07-20 00:26 UTC, merged