Apim/network troubleshooter
Azure/Azure-AppServices-Diagnostics-Portal pull request #1660
Opened 2022-07-20 00:35 UTC by atuannguyen1101

2022-08-07 18:54 UTC, yifguoMSFT commented on AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts
> +        { name: "VNet Integration", supportTopicId: "32683732", sapSupportTopicId: "5724df2a-a62a-59cc-83aa-1525fbc22377" }, // Function App\Networking\Outbound Connectivity
nitpick: please update the comment and order the entries by name

2022-08-07 19:18 UTC, yifguoMSFT requested changes

2022-08-07 19:18 UTC, yifguoMSFT commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-troubleshooter/network-troubleshooter.component.scss
> +    width: auto;
by changing these config, the Network Troubleshooter UI for other resources is also changed unexpectedly. Please revert the changes or figure out a way to make sure the change only effects for APIM

before
![image](https://user-images.githubusercontent.com/68874830/183307310-5e1c1ac3-875a-4a90-b2a4-48e6d93faf51.png)

after
![image](https://user-images.githubusercontent.com/68874830/183307289-b1af69d1-c5e4-4cbd-8244-7f9046588539.png)

2022-08-11 16:49 UTC, yifguoMSFT commented on AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts
> +        { name: "Outbound Connectivity", supportTopicId: "32820562", sapSupportTopicId: "8856038e-a071-236e-9823-41313ee4cb85" }, // Function App\Networking\Outbound Connectivity
did you remove the APIM support topic? Is it intentional?

2022-08-11 18:21 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts
> +        { name: "Outbound Connectivity", supportTopicId: "32820562", sapSupportTopicId: "8856038e-a071-236e-9823-41313ee4cb85" }, // Function App\Networking\Outbound Connectivity
Yes since we still want to keep the same Detector experience, and we have not found a way to link the Diagnostic tool to the Detector, we will keep it the same for the Case Flow submission for now.

2022-08-11 18:21 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-troubleshooter/network-troubleshooter.component.scss
> +    width: auto;
Ack, Pranav will address this.

2022-08-29 17:56 UTC, atuannguyen1101 commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-troubleshooter/network-troubleshooter.component.scss
> +    width: auto;
Fixed by using nested style class

2022-09-06 06:53 UTC, yifguoMSFT approved these changes

2022-11-04 15:38 UTC, merged