to allow editing monitoring and analysis detectors
Azure/Azure-AppServices-Diagnostics-Portal pull request #1818
Opened 2022-11-17 01:00 UTC by DarrelDonald

2022-11-18 18:01 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
> +    const path = "api/appsettings/SystemInvokers:ResourceIDString";
These three methods are essentially doing the same thing -
Making a call to api/appsettings/{appsettingName}. 
We can make the code extensible by writing a single method that accepts the app setting key as the parameter

2022-11-18 18:07 UTC, rekhaswaminathan requested changes

2022-11-18 18:07 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
Isn't this a part of appsettings?

2022-11-18 18:07 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
> +    var requestBranch = isSystemInvoker ? `dev/${this.userName.split("@")[0]}/detector/${this.publishingPackage.id.toLowerCase()}` : this.Branch;
I don't understand this part. If it's SystemInvoker we use dev/<user>/detector/<detectorid> branch?

2022-11-18 18:10 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/applens-docs/applens-docs.component.ts
> +              this.docsResource = sysResourceID;
Why are these calls getting being subscribed within each other if they are not dependent on the previous's one result? 
Eg; I don't see getDocumentationStagingBranch() using result from getDocumentationRoot() and same for getSystemInvokerResourceIdString() using result from getDocumentationStagingBranch() ?

2022-11-18 19:05 UTC, DarrelDonald commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
> +    var requestBranch = isSystemInvoker ? `dev/${this.userName.split("@")[0]}/detector/${this.publishingPackage.id.toLowerCase()}` : this.Branch;
yes. needs a branch to save to if not publishing immediately. also the repo were saving them in doesnt allow push to main so we need a branch so save to for pull requests too

2022-11-18 19:26 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
> +    var requestBranch = isSystemInvoker ? `dev/${this.userName.split("@")[0]}/detector/${this.publishingPackage.id.toLowerCase()}` : this.Branch;
Aren't we already doing it here? - https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/blob/ced3c9b9ba7e55fe25fcf0feef0d04cf8e1db40b/AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts#L585

2022-11-19 00:28 UTC, DarrelDonald commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
> +    var requestBranch = isSystemInvoker ? `dev/${this.userName.split("@")[0]}/detector/${this.publishingPackage.id.toLowerCase()}` : this.Branch;
this will use the id of the detector that monitoring was opened from instead of the monitoring detector id

2022-11-21 17:21 UTC, rekhaswaminathan commented on AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
> +    var requestBranch = isSystemInvoker ? `dev/${this.userName.split("@")[0]}/detector/${this.publishingPackage.id.toLowerCase()}` : this.Branch;
Got it. Thanks!

2022-11-21 17:49 UTC, rekhaswaminathan approved these changes

2022-11-21 21:41 UTC, rekhaswaminathan approved these changes

2022-11-21 21:41 UTC, merged