Restrict cross origin iframe access
Azure/Azure-AppServices-Diagnostics-Portal pull request #1837
Opened 2022-12-02 03:00 UTC by SharmaAjay19

## Overview
This PR aims to secure Applens by restricting who can embed AppLens in a browser iframe. This is needed for preventing against cross-site scripting attacks.

## Related Work Item
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2823

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Solution description
To prevent cross origin iframing we are adding the Content-Security-Policy header that tells browsers to enforce restrictions on iframing of our website. We will allow only certain few endpoints like ASC to be able to iframe AppLens.

### This PR:
Adds a new response header to a enforce cross origin iframing restrictions.

## How Can This Be Tested? <span>&#128269;</span>
You can create a simple index.html file with <iframe src="APPLENS_PROJECT_URL"/> and see that it will not render the project in the IFrame.

## Checklist <span>&#9989;</span>
- [x] I have looked over the diffs.
- [x] I have run the linter to catch any errors.
- [x] There are no errors from my changes on this branch.
- [x] I have ensured that my changes support accessibility and can be accessed with the keyboard alone
- [x] I have requested review on this PR.

## Extra Notes
This is just a starter list of allowed origins, it may expand to include more urls later.

2022-12-02 06:55 UTC, ShekharGupta1988 approved these changes

2022-12-02 17:24 UTC, hforeste requested changes

2022-12-02 17:24 UTC, hforeste commented on ApplensBackend/Middleware/RequestMiddlewarePublic.cs
> +            };
Can we add these in our appsettings and not harcode it?

2022-12-02 17:24 UTC, hforeste commented on ApplensBackend/Middleware/RequestMiddlewareNationalCloud.cs
> +                        allowedOrigin = "https://azuresupportcenter.microsoft.scloud/";
Same comment here. Can we add the azuresupportcenter urls in our appsettings versus harcode them.

2022-12-02 17:24 UTC, hforeste commented on ApplensBackend/Middleware/RequestMiddlewareNationalCloud.cs
> +                switch (websiteHostName)
Instead of switch case on `WEBSITE_HOSTNAME`, lets use the `CloudDomain` of the environment. 

```suggestion
                if (Configuration.IsAzureUSGovernment()) { ... }
```

See [MultiCloudExtensions](https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/blob/main/ApplensBackend/Extensions/MultiCloudExtensions.cs)

2022-12-03 00:55 UTC, SharmaAjay19 commented on ApplensBackend/Middleware/RequestMiddlewarePublic.cs
> +            };
Done

2022-12-03 00:55 UTC, SharmaAjay19 commented on ApplensBackend/Middleware/RequestMiddlewareNationalCloud.cs
> +                        allowedOrigin = "https://azuresupportcenter.microsoft.scloud/";
Done

2022-12-03 00:55 UTC, SharmaAjay19 commented on ApplensBackend/Middleware/RequestMiddlewareNationalCloud.cs
> +                switch (websiteHostName)
Done

2022-12-03 01:08 UTC, hforeste approved these changes

2022-12-03 01:09 UTC, merged