Enables Fleet detectors on for D&S blade.
Azure/Azure-AppServices-Diagnostics-Portal pull request #1984
Opened 2023-04-06 16:43 UTC by Ealianis

## Overview
Added the config files for new resource type `containerservice/fleets`, enabling 

## Related Work Item
[ADO Task](https://msazure.visualstudio.com/CloudNativeCompute/_workitems/edit/16713931)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist <span>&#9989;</span>
- [x] I have looked over the diffs.
- [x] I have run the linter to catch any errors.
- [x] There are no errors from my changes on this branch.
- [x] I have requested review on this PR.

## Extra Notes
PR will remain open as we discuss the quality of the detector that this is mapped to. It appears there is a design around a detector being a category of issues vs. a specific issue.

2023-04-06 23:05 UTC, nmallick1 requested changes

2023-04-07 23:37 UTC, Ealianis commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerservice/fleets/config.json
> +	"matchRegEx": "/Microsoft.ContainerService/managedClusters/",
Fixed.

2023-04-07 23:41 UTC, Ealianis commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerservice/fleets/config.json
> +		"armApiVersion": "2019-04-01"
@nmallick1 , does this API version reference the resource type's most recent API version?

2023-04-08 00:01 UTC, nmallick1 commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerservice/fleets/config.json
> +		"armApiVersion": "2019-04-01"
Yes, this is the ARM API version corresponding to the RP that has the /detectors and /detectors/{detectorId} API implementation.

2023-04-10 21:15 UTC, Ealianis commented on AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerservice/fleets/config.json
> +		"armApiVersion": "2019-04-01"
Updated

2023-04-12 01:00 UTC, merged