Add Linux Network Checking to Diagnose and Solve -> Connectivity Check
Azure/Azure-AppServices-Diagnostics-Portal pull request #2044
Opened 2023-05-18 21:24 UTC by CooperLink

## Overview

Updates linux to support the connectivity check api in VnetProxy

Change is required to support Network Checker work ongoing to enable Network Diagnostics from the Portal for Customers with common networking configuration
## Related Work Item

https://msazure.visualstudio.com/Antares/_workitems/edit/13004963/

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Solution description

### This PR:
Enables the Connectivity Check for Azure Functions Linux to allow customers to Diagnose and Solve typical network configuration issues. 

## How Can This Be Tested? <span>&#128269;</span>
This has been tested locally using Portal with Local Host 

TODO ...
## Checklist <span>&#9989;</span>
- [ ] I have looked over the diffs.
- [ ] I have run the linter to catch any errors.
- [ ] There are no errors from my changes on this branch.
- [ ] I have ensured that my changes support accessibility and can be accessed with the keyboard alone
- [ ] I have requested review on this PR.

## Screenshots Before Fix (if appropriate):

## Screenshots After Fix (if appropriate):

## Extra Notes

2023-05-19 16:29 UTC, yifguoMSFT approved these changes

2023-05-19 18:50 UTC, sidkri requested changes

2023-05-19 18:50 UTC, sidkri commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/functionsFlow.js
> +            isKuduAccessiblePromise = true; // Kudu not necessary for Network Validation on Linux
I'm unable to follow how this will work as all logic that depends on kudu will now fail.  We need to disable such functionality further down or have them route the calls to vnetproxy in cases where it can handle what kudu is used for.

2023-05-31 17:50 UTC, sidkri commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/functionsFlow.js
> +        if (!siteInfo.kind.includes("linux") && !await isKuduAccessiblePromise) {
Leave a comment explaining our rationale:
// Only check if kudu is accessible for windows SKU as linux doesn't rely on kudu

2023-05-31 17:52 UTC, sidkri commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetDnsWordings.js
> +                    title: `Validation Service Temporary Unavailable, cannot validate ${what}`,
hmmm, should we add "please try again later and contact support if needed"?

2023-05-31 20:12 UTC, CooperLink commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/functionsFlow.js
> +            isKuduAccessiblePromise = true; // Kudu not necessary for Network Validation on Linux
Sid and I discussed this issue in depth on Friday.  

There are two functions that are necessary to complete the FunctionFlow
- isKuduAccessible - Used to determine if the site can be accessed. If Kudu is not accessible for windows, Flow reverts to the bare minimum and just requests simple validation. For example, we are able to determine vnet integration without kudu for windows. When Kudu is accessible we do things like check the Private IP allocated to the worker.   When Kudu is not accessible Portal can do setting validation but, can't ping worker at all.

- isBackendAccessible - Used to determine if the net checker is available on Linux and Windows. If this is inaccessible, fallback to just checking poratl and what is checked from Kudu (windows).  If this is inaccessible for linux we only check portal settings and we do not check Function Specific stuff. For example we don't check Function Bindings.

2023-05-31 20:51 UTC, CooperLink commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/functionsFlow.js
> +        if (!siteInfo.kind.includes("linux") && !await isKuduAccessiblePromise) {
Updated with a comment

2023-05-31 20:52 UTC, CooperLink commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetDnsWordings.js
> +                    title: `Validation Service Temporary Unavailable, cannot validate ${what}`,
For windows we do not include that I am keeping it the same for right now

2023-06-02 20:26 UTC, sidkri commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetDnsConfigChecker.js
> +            // possible to add a conditional here, or possibly just TCPPing to Network Validation Service
Is this comment still relevant since we have the conditional now?

2023-06-02 20:27 UTC, yifguoMSFT approved these changes

2023-06-02 20:29 UTC, sidkri commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/functionsFlow.js
> +        if (siteInfo.kind.includes("container")){
Just realized a simplification but don't bother unless you have to modify this again and test:
we can just check for "container" at the top and return and avoid all confusing "linux" or "container" logic and keep it simply linux v/s windows.

2023-06-02 20:30 UTC, sidkri approved these changes

2023-06-02 21:16 UTC, CooperLink commented on AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetDnsConfigChecker.js
> +            // possible to add a conditional here, or possibly just TCPPing to Network Validation Service
I just removed this comment

2023-06-02 21:17 UTC, merged